//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC.Puzzles2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC.Puzzles2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | (\+|-)?[0-9]+
        ///Real            = &quot;a real number&quot; | (\+|-)?[0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///program         = line moreLines
        ///
        ///moreLines       =
        ///                | line moreLines
        ///
        ///line            = &quot;Monkey&quot; Integer &quot;:&quot; s_monkey
        ///                | &quot;Starting&quot; &quot;items&quot; &quot;:&quot; starting
        ///                | &quot;Operation&quot; &quot;:&quot; &quot;new&quot; &quot;=&quot; &quot;old&quot; operation
        ///                | &quot;Tes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day00Grammar {
            get {
                return ResourceManager.GetString("Day00Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day00Inputs {
            get {
                return ResourceManager.GetString("Day00Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///2000
        ///3000
        ///
        ///4000
        ///
        ///5000
        ///6000
        ///
        ///7000
        ///8000
        ///9000
        ///
        ///10000
        ///
        ///.
        /// </summary>
        internal static string Day01Inputs {
            get {
                return ResourceManager.GetString("Day01Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Y
        ///B X
        ///C Z.
        /// </summary>
        internal static string Day02Inputs {
            get {
                return ResourceManager.GetString("Day02Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vJrwpWtwJgWrhcsFMMfFFhFp
        ///jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
        ///PmmdzqPrVvPwwTWBwg
        ///wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
        ///ttgJtRGJQctTZtZT
        ///CrZsJsPPZsGzwwsLwLmpwMDw.
        /// </summary>
        internal static string Day03Inputs {
            get {
                return ResourceManager.GetString("Day03Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-4,6-8
        ///2-3,4-5
        ///5-7,7-9
        ///2-8,3-7
        ///6-6,4-6
        ///2-6,4-8.
        /// </summary>
        internal static string Day04Inputs {
            get {
                return ResourceManager.GetString("Day04Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [D]    
        ///[N] [C]    
        ///[Z] [M] [P]
        /// 1   2   3 
        ///
        ///move 1 from 2 to 1
        ///move 3 from 1 to 3
        ///move 2 from 2 to 1
        ///move 1 from 1 to 2.
        /// </summary>
        internal static string Day05Inputs {
            get {
                return ResourceManager.GetString("Day05Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mjqjpqmgbljsphdztnvjfqwrcgsmlb
        ///bvwbjplbgvbhsrlpgdmjqwftvncz
        ///nppdvjthqldpwncqszvftbrmjlhg
        ///nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg
        ///zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw.
        /// </summary>
        internal static string Day06Inputs {
            get {
                return ResourceManager.GetString("Day06Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | (\+|-)?[0-9]+
        ///Real            = &quot;a real number&quot; | [0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///program         = line moreLines
        ///
        ///moreLines       =
        ///                | line moreLines
        ///
        ///line            = &quot;$&quot; command
        ///                | &quot;dir&quot; Id c_dir
        ///                | Integer filename c_file
        ///
        ///command         = &quot;cd&quot; directory
        ///                | &quot;ls&quot; c_ls
        ///
        ///filename        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Grammar {
            get {
                return ResourceManager.GetString("Day07Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir a
        ///14848514 b.txt
        ///8504156 c.dat
        ///dir d
        ///$ cd a
        ///$ ls
        ///dir e
        ///29116 f
        ///2557 g
        ///62596 h.lst
        ///$ cd e
        ///$ ls
        ///584 i
        ///$ cd ..
        ///$ cd ..
        ///$ cd d
        ///$ ls
        ///4060174 j
        ///8033020 d.log
        ///5626152 d.ext
        ///7214296 k.
        /// </summary>
        internal static string Day07Inputs {
            get {
                return ResourceManager.GetString("Day07Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30373
        ///25512
        ///65332
        ///33549
        ///35390.
        /// </summary>
        internal static string Day08Inputs {
            get {
                return ResourceManager.GetString("Day08Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 4
        ///U 4
        ///L 3
        ///D 1
        ///R 4
        ///D 1
        ///L 5
        ///R 2.
        /// </summary>
        internal static string Day09Inputs {
            get {
                return ResourceManager.GetString("Day09Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 5
        ///U 8
        ///L 8
        ///D 3
        ///R 17
        ///D 10
        ///L 25
        ///U 20.
        /// </summary>
        internal static string Day09Inputs2 {
            get {
                return ResourceManager.GetString("Day09Inputs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | (\+|-)?[0-9]+
        ///Real            = &quot;a real number&quot; | (\+|-)?[0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///program         = line moreLines
        ///
        ///moreLines       =
        ///                | line moreLines
        ///
        ///line            = &quot;noop&quot; c_noop
        ///                | &quot;addx&quot; arg t_integer c_addx
        ///
        ///arg             = &quot;-&quot; Integer c_negate
        ///                | Integer
        ///
        ///#END
        ///.
        /// </summary>
        internal static string Day10Grammar {
            get {
                return ResourceManager.GetString("Day10Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addx 15
        ///addx -11
        ///addx 6
        ///addx -3
        ///addx 5
        ///addx -1
        ///addx -8
        ///addx 13
        ///addx 4
        ///noop
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx -35
        ///addx 1
        ///addx 24
        ///addx -19
        ///addx 1
        ///addx 16
        ///addx -11
        ///noop
        ///noop
        ///addx 21
        ///addx -15
        ///noop
        ///noop
        ///addx -3
        ///addx 9
        ///addx 1
        ///addx -3
        ///addx 8
        ///addx 1
        ///addx 5
        ///noop
        ///noop
        ///noop
        ///noop
        ///noop
        ///addx -36
        ///noop
        ///addx 1
        ///addx 7
        ///noop
        ///noop
        ///noop
        ///addx 2
        ///addx 6
        ///noop
        ///noop
        ///noop
        ///noop
        ///noop
        ///addx 1
        ///noop
        ///noop
        ///addx 7
        ///addx 1
        ///noop
        ///addx -13
        ///addx 13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Inputs {
            get {
                return ResourceManager.GetString("Day10Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | (\+|-)?[0-9]+
        ///Real            = &quot;a real number&quot; | (\+|-)?[0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///program         = line moreLines
        ///
        ///moreLines       =
        ///                | line moreLines
        ///
        ///line            = &quot;Monkey&quot; Integer &quot;:&quot; s_monkey
        ///                | &quot;Starting&quot; &quot;items&quot; &quot;:&quot; starting
        ///                | &quot;Operation&quot; &quot;:&quot; &quot;new&quot; &quot;=&quot; &quot;old&quot; operation
        ///                | &quot;Tes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Grammar {
            get {
                return ResourceManager.GetString("Day11Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey 0:
        ///  Starting items: 79, 98
        ///  Operation: new = old * 19
        ///  Test: divisible by 23
        ///    If true: throw to monkey 2
        ///    If false: throw to monkey 3
        ///
        ///Monkey 1:
        ///  Starting items: 54, 65, 75, 74
        ///  Operation: new = old + 6
        ///  Test: divisible by 19
        ///    If true: throw to monkey 2
        ///    If false: throw to monkey 0
        ///
        ///Monkey 2:
        ///  Starting items: 79, 60, 97
        ///  Operation: new = old * old
        ///  Test: divisible by 13
        ///    If true: throw to monkey 1
        ///    If false: throw to monkey 3
        ///
        ///Monkey 3:
        ///  Starting item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Inputs {
            get {
                return ResourceManager.GetString("Day11Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabqponm
        ///abcryxxl
        ///accszExk
        ///acctuvwj
        ///abdefghi.
        /// </summary>
        internal static string Day12Inputs {
            get {
                return ResourceManager.GetString("Day12Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | (\+|-)?[0-9]+
        ///Real            = &quot;a real number&quot; | (\+|-)?[0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///program         = line moreLines
        ///
        ///moreLines       =
        ///                | line moreLines
        ///
        ///line            = list
        ///
        ///list            = &quot;[&quot; c_openList elements &quot;]&quot; c_closeList
        ///
        ///elements        = 
        ///                | Integer c_number moreElements
        ///                | list more [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13Grammar {
            get {
                return ResourceManager.GetString("Day13Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1,1,3,1,1]
        ///[1,1,5,1,1]
        ///
        ///[[1],[2,3,4]]
        ///[[1],4]
        ///
        ///[9]
        ///[[8,7,6]]
        ///
        ///[[4,4],4,4]
        ///[[4,4],4,4,4]
        ///
        ///[7,7,7,7]
        ///[7,7,7]
        ///
        ///[]
        ///[3]
        ///
        ///[[[]]]
        ///[[]]
        ///
        ///[1,[2,[3,[4,[5,6,7]]]],8,9]
        ///[1,[2,[3,[4,[5,6,0]]]],8,9].
        /// </summary>
        internal static string Day13Inputs {
            get {
                return ResourceManager.GetString("Day13Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 498,4 -&gt; 498,6 -&gt; 496,6
        ///503,4 -&gt; 502,4 -&gt; 502,9 -&gt; 494,9.
        /// </summary>
        internal static string Day14Inputs {
            get {
                return ResourceManager.GetString("Day14Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor at x=2, y=18: closest beacon is at x=-2, y=15
        ///Sensor at x=9, y=16: closest beacon is at x=10, y=16
        ///Sensor at x=13, y=2: closest beacon is at x=15, y=3
        ///Sensor at x=12, y=14: closest beacon is at x=10, y=16
        ///Sensor at x=10, y=20: closest beacon is at x=10, y=16
        ///Sensor at x=14, y=17: closest beacon is at x=10, y=16
        ///Sensor at x=8, y=7: closest beacon is at x=2, y=10
        ///Sensor at x=2, y=0: closest beacon is at x=2, y=10
        ///Sensor at x=0, y=11: closest beacon is at x=2, y=10
        ///Sensor at x=20, y=14: closest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15Inputs {
            get {
                return ResourceManager.GetString("Day15Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///Integer         = &quot;an integer&quot; | [0-9]+
        ///
        ///#GRAMMAR
        ///
        ///program         = line moreLines
        ///
        ///moreLines       =
        ///                | line moreLines
        ///
        ///line            = &quot;Valve&quot; Id c_valve &quot;has&quot; &quot;flow&quot; &quot;rate&quot; &quot;=&quot; Integer &quot;;&quot; c_rate tunnels_
        ///
        ///tunnels_        = &quot;tunnel&quot; &quot;leads&quot; &quot;to&quot; &quot;valve&quot; tunnel_
        ///                | &quot;tunnels&quot; &quot;lead&quot; &quot;to&quot; &quot;valves&quot; tunnel_ moreTunnels
        ///
        ///tunnel_         = Id c_tunnel
        ///
        ///moreTunnels     =
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Grammar {
            get {
                return ResourceManager.GetString("Day16Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve AA has flow rate=0; tunnels lead to valves DD, II, BB
        ///Valve BB has flow rate=13; tunnels lead to valves CC, AA
        ///Valve CC has flow rate=2; tunnels lead to valves DD, BB
        ///Valve DD has flow rate=20; tunnels lead to valves CC, AA, EE
        ///Valve EE has flow rate=3; tunnels lead to valves FF, DD
        ///Valve FF has flow rate=0; tunnels lead to valves EE, GG
        ///Valve GG has flow rate=0; tunnels lead to valves FF, HH
        ///Valve HH has flow rate=22; tunnel leads to valve GG
        ///Valve II has flow rate=0; tunnels lead to valves A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Inputs {
            get {
                return ResourceManager.GetString("Day16Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt;&lt;&lt;&gt;&lt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&lt;&lt;&lt;&gt;&gt;&lt;&gt;&gt;&lt;&lt;&gt;&gt;.
        /// </summary>
        internal static string Day17Inputs {
            get {
                return ResourceManager.GetString("Day17Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,2,2
        ///1,2,2
        ///3,2,2
        ///2,1,2
        ///2,3,2
        ///2,2,1
        ///2,2,3
        ///2,2,4
        ///2,2,6
        ///1,2,5
        ///3,2,5
        ///2,1,5
        ///2,3,5.
        /// </summary>
        internal static string Day18Inputs {
            get {
                return ResourceManager.GetString("Day18Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,2,1
        ///2,2,4
        ///2,1,2
        ///1,2,2
        ///2,3,2
        ///3,2,2
        ///2,1,3
        ///1,2,3
        ///2,3,3
        ///3,2,3.
        /// </summary>
        internal static string Day18Inputs2 {
            get {
                return ResourceManager.GetString("Day18Inputs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint 1: Each ore robot costs 4 ore. Each clay robot costs 2 ore. Each obsidian robot costs 3 ore and 14 clay. Each geode robot costs 2 ore and 7 obsidian.
        ///Blueprint 2: Each ore robot costs 2 ore. Each clay robot costs 3 ore. Each obsidian robot costs 3 ore and 8 clay. Each geode robot costs 3 ore and 12 obsidian..
        /// </summary>
        internal static string Day19Inputs {
            get {
                return ResourceManager.GetString("Day19Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2
        ///-3
        ///3
        ///-2
        ///0
        ///4.
        /// </summary>
        internal static string Day20Inputs {
            get {
                return ResourceManager.GetString("Day20Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root: pppw + sjmn
        ///dbpl: 5
        ///cczh: sllz + lgvd
        ///zczc: 2
        ///ptdq: humn - dvpt
        ///dvpt: 3
        ///lfqf: 4
        ///humn: 5
        ///ljgn: 2
        ///sjmn: drzm * dbpl
        ///sllz: 4
        ///pppw: cczh / lfqf
        ///lgvd: ljgn * ptdq
        ///drzm: hmdt - zczc
        ///hmdt: 32.
        /// </summary>
        internal static string Day21Inputs {
            get {
                return ResourceManager.GetString("Day21Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         ...#
        ///        .#..
        ///        #...
        ///        ....
        ///...#.......#
        ///........#...
        ///..#....#....
        ///..........#.
        ///        ...#....
        ///        .....#..
        ///        .#......
        ///        ......#.
        ///
        ///10R5L5R10L4R5L5.
        /// </summary>
        internal static string Day22Inputs {
            get {
                return ResourceManager.GetString("Day22Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....#..
        ///..###.#
        ///#...#.#
        ///.#...##
        ///#.###..
        ///##.#.##
        ///.#..#...
        /// </summary>
        internal static string Day23Inputs {
            get {
                return ResourceManager.GetString("Day23Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day24Inputs {
            get {
                return ResourceManager.GetString("Day24Inputs", resourceCulture);
            }
        }
    }
}
