//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC.Puzzles2018.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC.Puzzles2018.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day00PuzzleInputs {
            get {
                return ResourceManager.GetString("Day00PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day00SampleInputs {
            get {
                return ResourceManager.GetString("Day00SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +16
        ///+9
        ///+11
        ///+13
        ///+11
        ///+3
        ///+8
        ///+9
        ///+14
        ///+16
        ///-5
        ///-15
        ///+5
        ///-7
        ///-5
        ///-18
        ///-9
        ///+2
        ///+1
        ///+18
        ///+15
        ///+6
        ///+19
        ///-9
        ///+1
        ///+15
        ///-10
        ///-3
        ///-18
        ///+7
        ///-1
        ///+7
        ///+6
        ///+13
        ///+10
        ///+10
        ///+9
        ///+18
        ///+2
        ///+15
        ///-19
        ///+13
        ///+8
        ///-18
        ///+6
        ///-12
        ///+10
        ///+5
        ///-6
        ///+14
        ///+8
        ///+2
        ///+2
        ///+12
        ///-2
        ///+5
        ///-11
        ///-2
        ///+7
        ///+7
        ///-19
        ///-6
        ///-1
        ///-12
        ///+16
        ///-2
        ///+13
        ///+17
        ///+15
        ///-9
        ///+3
        ///+16
        ///+13
        ///+14
        ///+17
        ///-10
        ///+1
        ///+3
        ///+10
        ///-18
        ///-1
        ///-15
        ///+5
        ///-16
        ///-7
        ///-9
        ///+18
        ///+17
        ///+3
        ///+8
        ///+7
        ///-3
        ///-11
        ///-19
        ///-8
        ///-10
        ///-11
        ///-5
        ///-1
        ///+19
        ///-8
        ///-9
        ///+11
        ///+16
        ///+11
        ///+3
        ///+17
        ///+14
        ///+9
        ///+15
        ///+7
        ///-15
        ///+16
        ///+6        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01PuzzleInputs {
            get {
                return ResourceManager.GetString("Day01PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1
        ///-2
        ///+3
        ///+1.
        /// </summary>
        internal static string Day01SampleInputs {
            get {
                return ResourceManager.GetString("Day01SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ybruvapdgixszyckwtfqjonsie
        ///mbruvapxghslyyckwtfqjonsie
        ///mbruvapdghslzyckwtkujonsie
        ///rwruvapdghxlzyckwtfqjcnsie
        ///obruvapdgtxlzyckwtfqionsie
        ///lbruvapdghxqzyckwtfqjfnsie
        ///mbrunapdghxlzyccatfqjonsie
        ///mbruvapdghxlzyokltfqjdnsie
        ///ybruvapdghxlzmckwtfqjmnsie
        ///mbruwaadghxdzyckwtfqjonsie
        ///muruvapdghxlzyckvtfqjonsim
        ///mbruvapdghxlkyckwtxqjonjie
        ///mbruvaqdghxlzyckwtfqjrnnie
        ///mwruvapdghdlzyckttfqjonsie
        ///mbruvapdgtelzyckwxfqjonsie
        ///mbruvapdohxlzvckwtfqjonhie
        ///mbrugapdgbxlzyckwtfqjynsie
        ///mbruvapdghxlzyckwtlqjonjiu
        ///mbruvapw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02PuzzleInputs {
            get {
                return ResourceManager.GetString("Day02PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcde
        ///fghij
        ///klmno
        ///pqrst
        ///fguij
        ///axcye
        ///wvxyz.
        /// </summary>
        internal static string Day02SampleInputs {
            get {
                return ResourceManager.GetString("Day02SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Integer         = &quot;an integer&quot; | [0-9]+
        ///
        ///#GRAMMAR
        ///
        ///line            = claimId location size
        ///
        ///claimId         = &quot;#&quot; Integer c_claimId
        ///
        ///location        = &quot;@&quot; Integer c_left &quot;,&quot; Integer c_top
        ///
        ///size            = &quot;:&quot; Integer c_width &quot;x&quot; Integer c_height
        ///
        ///#END
        ///.
        /// </summary>
        internal static string Day03Grammar {
            get {
                return ResourceManager.GetString("Day03Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 167,777: 23x12
        ///#2 @ 253,106: 10x25
        ///#3 @ 104,622: 11x25
        ///#4 @ 267,61: 14x16
        ///#5 @ 829,831: 19x10
        ///#6 @ 886,374: 22x12
        ///#7 @ 129,812: 18x17
        ///#8 @ 972,677: 14x17
        ///#9 @ 123,249: 12x14
        ///#10 @ 669,330: 11x21
        ///#11 @ 657,629: 29x28
        ///#12 @ 961,341: 14x16
        ///#13 @ 921,321: 10x27
        ///#14 @ 418,646: 13x10
        ///#15 @ 94,106: 24x22
        ///#16 @ 570,515: 23x18
        ///#17 @ 476,666: 29x23
        ///#18 @ 28,430: 7x4
        ///#19 @ 943,766: 10x19
        ///#20 @ 120,528: 25x22
        ///#21 @ 801,611: 4x6
        ///#22 @ 455,766: 20x20
        ///#23 @ 12,560: 29x29
        ///#24 @ 694,858: 29x28
        ///# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03PuzzleInputs {
            get {
                return ResourceManager.GetString("Day03PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 1,3: 4x4
        ///#2 @ 3,1: 4x4
        ///#3 @ 5,5: 2x2.
        /// </summary>
        internal static string Day03SampleInputs {
            get {
                return ResourceManager.GetString("Day03SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | [0-9]+
        ///Real            = &quot;a real number&quot; | [0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///line            = timestamp event
        ///
        ///timestamp       = &quot;[&quot; Integer c_year &quot;-&quot; Integer c_month &quot;-&quot; Integer c_day Integer c_hour &quot;:&quot; Integer c_minute &quot;]&quot; t_timestamp
        ///
        ///event           = &quot;Guard&quot; &quot;#&quot; Integer c_guardId &quot;begins&quot; &quot;shift&quot; t_beginsShift
        ///                | &quot;falls&quot; &quot;asleep&quot; t_fall [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Grammar {
            get {
                return ResourceManager.GetString("Day04Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-09-17 23:48] Guard #1307 begins shift
        ///[1518-06-03 00:00] Guard #3217 begins shift
        ///[1518-07-28 00:49] falls asleep
        ///[1518-03-30 00:57] falls asleep
        ///[1518-07-01 23:58] Guard #409 begins shift
        ///[1518-04-13 00:25] wakes up
        ///[1518-04-09 00:22] wakes up
        ///[1518-11-02 00:41] falls asleep
        ///[1518-11-21 00:23] falls asleep
        ///[1518-05-03 00:59] wakes up
        ///[1518-11-21 00:02] Guard #1459 begins shift
        ///[1518-08-18 00:27] wakes up
        ///[1518-08-09 00:48] falls asleep
        ///[1518-09-23 00:23] falls asleep
        ///[1518-03-29 23:57]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04PuzzleInputs {
            get {
                return ResourceManager.GetString("Day04PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-11-01 00:00] Guard #10 begins shift
        ///[1518-11-01 00:05] falls asleep
        ///[1518-11-01 00:25] wakes up
        ///[1518-11-01 00:30] falls asleep
        ///[1518-11-01 00:55] wakes up
        ///[1518-11-01 23:58] Guard #99 begins shift
        ///[1518-11-02 00:40] falls asleep
        ///[1518-11-02 00:50] wakes up
        ///[1518-11-03 00:05] Guard #10 begins shift
        ///[1518-11-03 00:24] falls asleep
        ///[1518-11-03 00:29] wakes up
        ///[1518-11-04 00:02] Guard #99 begins shift
        ///[1518-11-04 00:36] falls asleep
        ///[1518-11-04 00:46] wakes up
        ///[1518-11-05 00:03] Guard #99 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04SampleInputs {
            get {
                return ResourceManager.GetString("Day04SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKkOohaAXxHrjUbByYuFfJMmOoZdDWVGgvwzZzUuUrRueERkIiKhnNpPdDXTtxMmwLlWGBbgTtoOmHOofSsFhrwWRWwytTwgGrRWYdcCUYyuqQHhpPiILPaApeElEeaAjJVvoiICIicdDOmnNMNZznoOgJmMFfjcCCcxXAaWiIwyYWwaAakBbLlJRrBbbBQqXrRNnHhcvVCxZzjKnrRNsSgGvVMmrqQWaAXxwRaAbHhBLlfkKCmMchiIHwRZJUujVvMmzrPsSpWZyYAaznHhNlLTtfSssSFuYjJyUWVvLlwqWZzqdDvVQNDdnzZGzZFqQfXxoOuUCcgRrSsHhbFfJPpjBdDyllLLdOoBXxtTqQRdDrrRbAalLyYvVqQYoOyDrRfFfFKZzkXxxAyAGgRNnrrRbJjzZWwBPpzZnNaYvVUsJjSRgHeEEehwWGrvVuZzfSsJjFaoOXesSDdHhwWEHwWMKkmkKeEABZzbahtTHhMpPxxXbTttTBhHXVvlLNng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05PuzzleInputs {
            get {
                return ResourceManager.GetString("Day05PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dabAcCaCBAcCcaDA.
        /// </summary>
        internal static string Day05SampleInputs {
            get {
                return ResourceManager.GetString("Day05SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81, 46
        ///330, 289
        ///171, 261
        ///248, 97
        ///142, 265
        ///139, 293
        ///309, 208
        ///315, 92
        ///72, 206
        ///59, 288
        ///95, 314
        ///126, 215
        ///240, 177
        ///78, 64
        ///162, 168
        ///75, 81
        ///271, 258
        ///317, 223
        ///210, 43
        ///47, 150
        ///352, 116
        ///316, 256
        ///269, 47
        ///227, 343
        ///125, 290
        ///245, 310
        ///355, 301
        ///251, 282
        ///353, 107
        ///254, 298
        ///212, 128
        ///60, 168
        ///318, 254
        ///310, 303
        ///176, 345
        ///110, 109
        ///217, 338
        ///344, 330
        ///231, 349
        ///259, 208
        ///201, 57
        ///200, 327
        ///354, 111
        ///166, 214
        ///232, 85
        ///96, 316
        ///151, 288
        ///217, 339
        ///62, 221
        ///307, 68.
        /// </summary>
        internal static string Day06PuzzleInputs {
            get {
                return ResourceManager.GetString("Day06PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, 1
        ///1, 6
        ///8, 3
        ///3, 4
        ///5, 5
        ///8, 9.
        /// </summary>
        internal static string Day06SampleInputs {
            get {
                return ResourceManager.GetString("Day06SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Z must be finished before step V can begin.
        ///Step V must be finished before step K can begin.
        ///Step M must be finished before step Q can begin.
        ///Step E must be finished before step X can begin.
        ///Step J must be finished before step W can begin.
        ///Step L must be finished before step O can begin.
        ///Step Q must be finished before step T can begin.
        ///Step Y must be finished before step P can begin.
        ///Step X must be finished before step R can begin.
        ///Step T must be finished before step U can begin.
        ///Step I must  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07PuzzleInputs {
            get {
                return ResourceManager.GetString("Day07PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step C must be finished before step A can begin.
        ///Step C must be finished before step F can begin.
        ///Step A must be finished before step B can begin.
        ///Step A must be finished before step D can begin.
        ///Step B must be finished before step E can begin.
        ///Step D must be finished before step E can begin.
        ///Step F must be finished before step E can begin..
        /// </summary>
        internal static string Day07SampleInputs {
            get {
                return ResourceManager.GetString("Day07SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 11 6 3 5 5 3 4 1 9 0 7 1 2 1 6 9 1 9 1 1 2 1 2 1 1 2 3 1 6 0 9 1 4 3 8 8 3 6 1 1 2 1 1 2 2 3 1 7 0 10 4 1 1 3 9 8 5 6 2 6 1 3 2 3 3 1 3 3 2 1 2 3 7 1 6 0 6 3 1 1 9 9 4 1 3 1 3 2 3 1 9 0 10 9 5 5 2 5 9 1 5 4 2 2 1 3 2 1 1 2 1 2 1 7 0 9 9 1 3 4 5 9 7 6 8 2 2 3 1 1 1 3 1 4 2 3 2 1 3 3 7 1 6 0 10 8 6 1 7 3 3 4 1 1 8 3 2 1 3 1 1 1 8 0 11 3 5 9 3 8 1 2 9 4 1 6 3 3 2 1 2 1 2 1 1 6 0 6 3 1 7 4 6 7 2 1 3 1 1 1 1 5 2 2 1 5 1 3 5 1 5 0 8 4 9 8 8 4 6 2 1 1 3 3 1 1 1 6 0 11 2 8 7 5 1 5 9 2 8 1 2 1 2 3 3 3 3 1 9 0 11 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08PuzzleInputs {
            get {
                return ResourceManager.GetString("Day08PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 3 0 3 10 11 12 1 1 0 1 99 2 1 1 2.
        /// </summary>
        internal static string Day08SampleInputs {
            get {
                return ResourceManager.GetString("Day08SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 455 players; last marble is worth 71223 points.
        /// </summary>
        internal static string Day09PuzzleInputs {
            get {
                return ResourceManager.GetString("Day09PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 players; last marble is worth 25 points: high score is 32
        ///10 players; last marble is worth 1618 points: high score is 8317
        ///13 players; last marble is worth 7999 points: high score is 146373
        ///17 players; last marble is worth 1104 points: high score is 2764
        ///21 players; last marble is worth 6111 points: high score is 54718
        ///30 players; last marble is worth 5807 points: high score is 37305.
        /// </summary>
        internal static string Day09SampleInputs {
            get {
                return ResourceManager.GetString("Day09SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#DEFINITIONS
        ///
        ///Id              = &quot;an identifier&quot; | [_A-Za-z][_A-Za-z0-9]*
        ///String          = &quot;a string&quot; | &apos;[.]*&apos;
        ///Integer         = &quot;an integer&quot; | (\+|-)?[0-9]+
        ///Real            = &quot;a real number&quot; | [0-9]+\.[0-9]+
        ///
        ///#GRAMMAR
        ///
        ///line            = position velocity
        ///
        ///position        = &quot;position&quot; d_test1 &quot;=&quot; d_test2 vector c_position
        ///
        ///velocity        = &quot;velocity&quot; &quot;=&quot; vector c_velocity
        ///
        ///vector          = d_test3 &quot;&lt;&quot; d_test4 Integer c_x &quot;,&quot; Integer c_y &quot;&gt;&quot;
        ///
        ///vectors         = &quot;&lt;&quot; sign Integer c_x &quot;,&quot; si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Grammar {
            get {
                return ResourceManager.GetString("Day10Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt;-42601, -53357&gt; velocity=&lt; 4,  5&gt;
        ///position=&lt; 10946,  43042&gt; velocity=&lt;-1, -4&gt;
        ///position=&lt; 21657,  32332&gt; velocity=&lt;-2, -3&gt;
        ///position=&lt;-42617,  53749&gt; velocity=&lt; 4, -5&gt;
        ///position=&lt;-21225, -53349&gt; velocity=&lt; 2,  5&gt;
        ///position=&lt; 10929, -42647&gt; velocity=&lt;-1,  4&gt;
        ///position=&lt; 53758,  43040&gt; velocity=&lt;-5, -4&gt;
        ///position=&lt; 53745,  21622&gt; velocity=&lt;-5, -2&gt;
        ///position=&lt;-42602,  32332&gt; velocity=&lt; 4, -3&gt;
        ///position=&lt; 53741, -42644&gt; velocity=&lt;-5,  4&gt;
        ///position=&lt; 10918,  21622&gt; velocity=&lt;-1, -2&gt;
        ///position=&lt; 43075, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10PuzzleInputs {
            get {
                return ResourceManager.GetString("Day10PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt; 9,  1&gt; velocity=&lt; 0,  2&gt;
        ///position=&lt; 7,  0&gt; velocity=&lt;-1,  0&gt;
        ///position=&lt; 3, -2&gt; velocity=&lt;-1,  1&gt;
        ///position=&lt; 6, 10&gt; velocity=&lt;-2, -1&gt;
        ///position=&lt; 2, -4&gt; velocity=&lt; 2,  2&gt;
        ///position=&lt;-6, 10&gt; velocity=&lt; 2, -2&gt;
        ///position=&lt; 1,  8&gt; velocity=&lt; 1, -1&gt;
        ///position=&lt; 1,  7&gt; velocity=&lt; 1,  0&gt;
        ///position=&lt;-3, 11&gt; velocity=&lt; 1, -2&gt;
        ///position=&lt; 7,  6&gt; velocity=&lt;-1, -1&gt;
        ///position=&lt;-2,  3&gt; velocity=&lt; 1,  0&gt;
        ///position=&lt;-4,  3&gt; velocity=&lt; 2,  0&gt;
        ///position=&lt;10, -3&gt; velocity=&lt;-1,  1&gt;
        ///position=&lt; 5, 11&gt; velocity=&lt; 1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10SampleInputs {
            get {
                return ResourceManager.GetString("Day10SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7315.
        /// </summary>
        internal static string Day11PuzzleInputs {
            get {
                return ResourceManager.GetString("Day11PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///42.
        /// </summary>
        internal static string Day11SampleInputs {
            get {
                return ResourceManager.GetString("Day11SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial state: #.##.###.#.##...##..#..##....#.#.#.#.##....##..#..####..###.####.##.#..#...#..######.#.....#..##...#
        ///
        ///.#.#. =&gt; .
        ///...#. =&gt; #
        ///..##. =&gt; .
        ///....# =&gt; .
        ///##.#. =&gt; #
        ///.##.# =&gt; #
        ///.#### =&gt; #
        ///#.#.# =&gt; #
        ///#..#. =&gt; #
        ///##..# =&gt; .
        ///##### =&gt; .
        ///...## =&gt; .
        ///.#... =&gt; .
        ///###.. =&gt; #
        ///#..## =&gt; .
        ///#...# =&gt; .
        ///.#..# =&gt; #
        ///.#.## =&gt; .
        ///#.#.. =&gt; #
        ///..... =&gt; .
        ///####. =&gt; .
        ///##.## =&gt; #
        ///..### =&gt; #
        ///#.... =&gt; .
        ///###.# =&gt; .
        ///.##.. =&gt; #
        ///#.### =&gt; #
        ///..#.# =&gt; .
        ///.###. =&gt; #
        ///##... =&gt; #
        ///#.##. =&gt; #
        ///..#.. =&gt; #.
        /// </summary>
        internal static string Day12PuzzleInputs {
            get {
                return ResourceManager.GetString("Day12PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial state: #..#.#..##......###...###
        ///
        ///..... =&gt; .
        ///....# =&gt; .
        ///...#. =&gt; .
        ///...## =&gt; #
        ///..#.. =&gt; #
        ///..#.# =&gt; .
        ///..##. =&gt; .
        ///..### =&gt; .
        ///.#... =&gt; #
        ///.#..# =&gt; .
        ///.#.#. =&gt; #
        ///.#.## =&gt; #
        ///.##.. =&gt; #
        ///.##.# =&gt; .
        ///.###. =&gt; .
        ///.#### =&gt; #
        ///#.... =&gt; .
        ///#...# =&gt; .
        ///#..#. =&gt; .
        ///#..## =&gt; .
        ///#.#.. =&gt; .
        ///#.#.# =&gt; #
        ///#.##. =&gt; .
        ///#.### =&gt; #
        ///##... =&gt; .
        ///##..# =&gt; .
        ///##.#. =&gt; #
        ///##.## =&gt; #
        ///###.. =&gt; #
        ///###.# =&gt; #
        ///####. =&gt; #
        ///##### =&gt; .
        ///.
        /// </summary>
        internal static string Day12SampleInputs {
            get {
                return ResourceManager.GetString("Day12SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                /-----------------------\        /---------------\  /--------------\                                                                   
        ///               |                 /-----+--------+---------------+--+--------------+-----------------------------------------\                         
        ///               |                 |     |        |            /--+--+--------------+-----------------------------------------+----------------\        
        ///               |               /-+-----+--------+------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13PuzzleInputs {
            get {
                return ResourceManager.GetString("Day13PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /-&gt;-\        
        ///|   |  /----\
        ///| /-+--+-\  |
        ///| | |  | v  |
        ///\-+-/  \-+--/
        ///  \------/  .
        /// </summary>
        internal static string Day13SampleInputs {
            get {
                return ResourceManager.GetString("Day13SampleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /&gt;-&lt;\  
        ///|   |  
        ///| /&lt;+-\
        ///| | | v
        ///\&gt;+&lt;/ |
        ///  |   ^
        ///  \&lt;-&gt;/.
        /// </summary>
        internal static string Day13SampleInputs2 {
            get {
                return ResourceManager.GetString("Day13SampleInputs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 598701.
        /// </summary>
        internal static string Day14PuzzleInputs {
            get {
                return ResourceManager.GetString("Day14PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///5
        ///18
        ///2018.
        /// </summary>
        internal static string Day14SampleInput {
            get {
                return ResourceManager.GetString("Day14SampleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51589
        ///01245
        ///92510
        ///59414.
        /// </summary>
        internal static string Day14SampleInputs2 {
            get {
                return ResourceManager.GetString("Day14SampleInputs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #DEFINITIONS
        ///
        ///ShowVisualization = true
        ///InitialHealth = 200
        ///ElfAttackPower = 3
        ///
        ///#INPUTS
        ///
        ///################################
        ///##############.#################
        ///##############...###############
        ///#..#######G.#....###############
        ///##.#####.#G....#.###############
        ///##..###.......##################
        ///###.####..G.G.##################
        ///###.##G.......##################
        ///###.G.....#...G######.##########
        ///###GGG..#......####E...#########
        ///###.GG.....########..#..#..#####
        ///#########.G...G.........#....###
        ///######## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15PuzzleInputs {
            get {
                return ResourceManager.GetString("Day15PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #######
        ///#.G...#
        ///#...EG#
        ///#.#.#G#
        ///#..G#E#
        ///#.....#
        ///#######.
        /// </summary>
        internal static string Day15SampleInputs01 {
            get {
                return ResourceManager.GetString("Day15SampleInputs01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #######
        ///#G..#E#
        ///#E#E.E#
        ///#G.##.#
        ///#...#E#
        ///#...E.#
        ///#######
        ///.
        /// </summary>
        internal static string Day15SampleInputs02 {
            get {
                return ResourceManager.GetString("Day15SampleInputs02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #######
        ///#E..EG#
        ///#.#G.E#
        ///#E.##E#
        ///#G..#.#
        ///#..E#.#
        ///#######.
        /// </summary>
        internal static string Day15SampleInputs03 {
            get {
                return ResourceManager.GetString("Day15SampleInputs03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #######
        ///#E.G#.#
        ///#.#G..#
        ///#G.#.G#
        ///#G..#.#
        ///#...E.#
        ///#######.
        /// </summary>
        internal static string Day15SampleInputs04 {
            get {
                return ResourceManager.GetString("Day15SampleInputs04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #######
        ///#.E...#
        ///#.#..G#
        ///#.###.#
        ///#E#G#G#
        ///#...#G#
        ///#######.
        /// </summary>
        internal static string Day15SampleInputs05 {
            get {
                return ResourceManager.GetString("Day15SampleInputs05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #########
        ///#G......#
        ///#.E.#...#
        ///#..##..G#
        ///#...##..#
        ///#...#...#
        ///#.G...G.#
        ///#.....G.#
        ///#########.
        /// </summary>
        internal static string Day15SampleInputs06 {
            get {
                return ResourceManager.GetString("Day15SampleInputs06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################
        ///#######.G...####################
        ///#########...####################
        ///#########.G.####################
        ///#########.######################
        ///#########.######################
        ///#########G######################
        ///#########.#...##################
        ///#########.....#..###############
        ///########...G....###.....########
        ///#######............G....########
        ///#######G....G.....G....#########
        ///######..G.....#####..G...#######
        ///######...G...#######......######
        ///#####.......#########....G..E###
        ///## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15SampleInputs07 {
            get {
                return ResourceManager.GetString("Day15SampleInputs07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################
        ///#####################...########
        ///###################....G########
        ///###################....#########
        ///#######.##########......########
        ///#######G#########........#######
        ///#######G#######.G.........######
        ///#######.######..G.........######
        ///#######.......##.G...G.G..######
        ///########..##..#....G......G#####
        ///############...#.....G.....#####
        ///#...#######..........G.#...#####
        ///#...#######...#####G......######
        ///##...######..#######G.....#.##.#
        ///###.G.#####.#########G.........#
        ///## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15SampleInputs08 {
            get {
                return ResourceManager.GetString("Day15SampleInputs08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################
        ///#############################..#
        ///#############################..#
        ///#############################..#
        ///###########################...##
        ///##########################..####
        ///###########..#G.#########G..####
        ///#########G........#######....###
        ///#########...G.......G##........#
        ///#######G.................E...###
        ///#######.####...####..G..#...####
        ///######...#.........G..###....###
        ///#####....#....#####...####...###
        ///####.........#######.....#....##
        ///#.G..G.G..#G#########...G.....##
        ///#. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15SampleInputs09 {
            get {
                return ResourceManager.GetString("Day15SampleInputs09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before: [0, 0, 2, 2]
        ///9 2 3 0
        ///After:  [4, 0, 2, 2]
        ///
        ///Before: [2, 1, 2, 3]
        ///0 1 2 3
        ///After:  [2, 1, 2, 2]
        ///
        ///Before: [3, 1, 3, 1]
        ///9 0 2 2
        ///After:  [3, 1, 6, 1]
        ///
        ///Before: [2, 0, 0, 3]
        ///15 0 3 3
        ///After:  [2, 0, 0, 0]
        ///
        ///Before: [0, 3, 3, 2]
        ///3 1 3 1
        ///After:  [0, 1, 3, 2]
        ///
        ///Before: [2, 3, 3, 2]
        ///8 2 2 3
        ///After:  [2, 3, 3, 9]
        ///
        ///Before: [3, 2, 3, 2]
        ///2 1 0 3
        ///After:  [3, 2, 3, 1]
        ///
        ///Before: [3, 3, 2, 0]
        ///4 1 2 3
        ///After:  [3, 3, 2, 1]
        ///
        ///Before: [1, 2, 3, 2]
        ///9 1 1 3
        ///After:  [1, 2, 3, 4]
        ///
        ///Before: [0, 2, 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16PuzzleInputs {
            get {
                return ResourceManager.GetString("Day16PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y=1195, x=558..562
        ///x=522, y=879..891
        ///x=466, y=1293..1304
        ///y=558, x=550..556
        ///x=543, y=1128..1141
        ///x=574, y=1496..1500
        ///x=533, y=1053..1064
        ///x=434, y=1130..1144
        ///y=1723, x=487..491
        ///y=1000, x=512..532
        ///y=111, x=505..524
        ///y=997, x=520..525
        ///x=484, y=76..87
        ///y=325, x=415..427
        ///x=463, y=1236..1248
        ///x=508, y=364..377
        ///x=490, y=1748..1759
        ///x=477, y=876..890
        ///y=781, x=453..464
        ///x=557, y=941..944
        ///y=24, x=519..531
        ///x=432, y=930..941
        ///x=571, y=175..185
        ///x=462, y=668..694
        ///x=570, y=1740..1756
        ///x=516, y=158..172
        ///y= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day17PuzzleInputs {
            get {
                return ResourceManager.GetString("Day17PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x=495, y=2..7
        ///y=7, x=495..501
        ///x=501, y=3..7
        ///x=498, y=2..4
        ///x=506, y=1..2
        ///x=498, y=10..13
        ///x=504, y=10..13
        ///y=13, x=498..504.
        /// </summary>
        internal static string Day17SampleInputs01 {
            get {
                return ResourceManager.GetString("Day17SampleInputs01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .|||.#..|##.#||..#.|..|..||||..#|##.##..#...|.....
        ///.|#.|#..##...|#.........#.#..#..|#.|#|##..#.#|..#.
        ///#....#|.#|.###||..#.|...|.|.#........#.|.#.#|..#..
        ///|..|#....|#|...#.#..||.#..||......#.........|....|
        ///.|.|..#|...#.|.###.|...||.|.|..|...|#|.#..|.|..|.|
        ///#.....||.#..|..|..||#.||#..|.||..||##.......#.....
        ///||.#..........|....##...|..#.|..#..#|#.#....#..#.#
        ///.#.#|.|.|.##|..#......|...#||..#.||..|..|#....|##.
        ///#.#..||.|...#|...|..#.#.||#.||.#.|.....|##.|....#.
        ///.#......||.|#......#|#.|...||...||##...#...# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day18PuzzleInputs {
            get {
                return ResourceManager.GetString("Day18PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#.#...|#.
        ///.....#|##|
        ///.|..|...#.
        ///..|#.....#
        ///#.#|||#|#|
        ///...#.||...
        ///.|....|...
        ///||...#|.#|
        ///|.||||..|.
        ///...#.|..|..
        /// </summary>
        internal static string Day18SampleInputs01 {
            get {
                return ResourceManager.GetString("Day18SampleInputs01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..|..|.|.|.||..#.#|...|..#.|.........|.......|..#.
        ///#.|.........|||....#....|....##||.....|.|.........
        ///..||......#.#||#.#.......#..#.#.###...|.#..#...#..
        ///|....#....|.##.##.....##...##|..|....|..|#||...###
        ///#|...|.#|..|......#.##....#|....|...|#......|.#|.|
        ///..|....##.##.#..||##...#..##|......|...|#.||.#.#..
        ///.#...#||...........#|.....|##....#.#...|#.|###..|.
        ///||....#.#.|...||...###|.|#.....#.|#.|#...#.#.|...#
        ///...#.....||.......#....#|###|####..|#|.###..||.#.#
        ///|#|...||..##.||.||..#.#.|..#...#..|........# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day18SampleInputs02 {
            get {
                return ResourceManager.GetString("Day18SampleInputs02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ip 4
        ///addi 4 16 4
        ///seti 1 5 1
        ///seti 1 2 2
        ///mulr 1 2 3
        ///eqrr 3 5 3
        ///addr 3 4 4
        ///addi 4 1 4
        ///addr 1 0 0
        ///addi 2 1 2
        ///gtrr 2 5 3
        ///addr 4 3 4
        ///seti 2 7 4
        ///addi 1 1 1
        ///gtrr 1 5 3
        ///addr 3 4 4
        ///seti 1 9 4
        ///mulr 4 4 4
        ///addi 5 2 5
        ///mulr 5 5 5
        ///mulr 4 5 5
        ///muli 5 11 5
        ///addi 3 1 3
        ///mulr 3 4 3
        ///addi 3 18 3
        ///addr 5 3 5
        ///addr 4 0 4
        ///seti 0 3 4
        ///setr 4 2 3
        ///mulr 3 4 3
        ///addr 4 3 3
        ///mulr 4 3 3
        ///muli 3 14 3
        ///mulr 3 4 3
        ///addr 5 3 5
        ///seti 0 4 0
        ///seti 0 5 4.
        /// </summary>
        internal static string Day19PuzzleInputs {
            get {
                return ResourceManager.GetString("Day19PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day19PuzzleInputsOptimized {
            get {
                return ResourceManager.GetString("Day19PuzzleInputsOptimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ip 0
        ///seti 5 0 1
        ///seti 6 0 2
        ///addi 0 1 0
        ///addr 1 2 3
        ///setr 1 0 0
        ///seti 8 0 4
        ///seti 9 0 5.
        /// </summary>
        internal static string Day19SampleInputs01 {
            get {
                return ResourceManager.GetString("Day19SampleInputs01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^NWWWNNNNNWNWNWSWNNNNENWNWSSWWSWWSEEENESSSWSSEESWSEENNE(NWWWEEES|)ESSSW(WSESE(N|ESWWWWSESWWWWWWNENNESEE(SWWEEN|)NWNN(ESE(SEWN|)N|WWNWSWNWNEENNWSWNWSWWNNWSWNNNWNEENEEESSENNE(ENNNNWNENEENWNNNEESESW(WNSE|)SEESENENWWNEENESESWSEESSENESSWSSSEEESSENNESENNEESWSSWSEEEENNESSENENNEESSW(N|SWSSWWWSWWSSWSSWWSWSSSESEENENWNN(EEEENNEEENESSSESSENNNNNW(NNENWNN(WSWSSE(SWWSWWN(NE(E|S)|WWSESWS(WNSE|)E)|N)|NNEESWSEESSSSEENNESESWSWWWW(SSEEN(EESENESENNW(NNNNEEEEENEESESWW(WWSSWNWN(WSSESESSSW(WWSSWWSWNNWN(WWSSE(N|ESSSSWWNNWWN(EEESSNN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day20PuzzleInputs {
            get {
                return ResourceManager.GetString("Day20PuzzleInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^WNE$.
        /// </summary>
        internal static string Day20SampleInputs01 {
            get {
                return ResourceManager.GetString("Day20SampleInputs01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^ENWWW(NEEE|SSE(EE|N))$.
        /// </summary>
        internal static string Day20SampleInputs02 {
            get {
                return ResourceManager.GetString("Day20SampleInputs02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^ENNWSWW(NEWS|)SSSEEN(WNSE|)EE(SWEN|)NNN$.
        /// </summary>
        internal static string Day20SampleInputs03 {
            get {
                return ResourceManager.GetString("Day20SampleInputs03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^ESSWWN(E|NNENN(EESS(WNSE|)SSS|WWWSSSSE(SW|NNNE)))$.
        /// </summary>
        internal static string Day20SampleInputs04 {
            get {
                return ResourceManager.GetString("Day20SampleInputs04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^WSSEESWWWNW(S|NENNEEEENN(ESSSSW(NWSW|SSEN)|WSWWN(E|WWS(E|SS))))$.
        /// </summary>
        internal static string Day20SampleInputs05 {
            get {
                return ResourceManager.GetString("Day20SampleInputs05", resourceCulture);
            }
        }
    }
}
